version: '3.8'

services:
  m10web:
    build: .
    container_name: m10web
    restart: always
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/app
    depends_on:
      - database_m10web
    environment:
      - DATABASE_URL=mysql://root:root@database_m10web:3306/m10web?reconnect=true

  database_m10web:
    container_name: database_m10web
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - pgdata:/data/mysql
    env_file:
      - .env

volumes:
  pgdata: ~